### ISSUE TITLE
repo Empty

### ISSUE THREAD

**Issue by AdelysAlberto** [CodelyTV/typescript-ddd-skeleton#1]
Hola, estaba viendo el video de youtube de clean architecture y vine a ver el modelo ejemplo en Typescript, pero esta vacio.

Es por alguna razon tecnica que ya no va?

**Comment by rgomezcasas** [comment]
Ha sido movido a https://github.com/CodelyTV/typescript-ddd-example 😊

¡Un saludo!

**Comment by JavierCane** [comment]
Thx for reporting!

Added a little note in [the repo readme](https://github.com/CodelyTV/typescript-ddd-skeleton) in order to avoid further confusions 😊 🤟
