### ISSUE TITLE
Middleware question

### ISSUE THREAD

**Issue by jvegaf** [CodelyTV/typescript-ddd-skeleton#76]
Hi,

How can put a middleware in a route? I tried several times, but I have not been able to achieve it.

Thanks !

**Comment by JavierCane** [comment]
Hi!

One alternative would be decorating your use case 🙂

**Comment by jvegaf** [comment]
Hi Javier, 

After many attempts I managed to achieve it !

in the below example, we have two middleware's (authChecker and userOwnChecker) chained on the route before the controller

```
const jobOpeningPutController: JobOpeningPutController = container.get(
    'App.controllers.jobOpenings.JobOpeningPutController'
  );

  router.put('/job_openings/:id', authChecker, userOwnChecker, (req: Request, res: Response) =>
    jobOpeningPutController.run(req, res)
  );
```
