### ISSUE TITLE
Is there a course of this?

### ISSUE THREAD

**Issue by rpalaciosg** [CodelyTV/typescript-ddd-skeleton#95]
Hola amigos, de codely, quiero aprender DDD o arquitectura exgonal, empece aprender typescript, hay un curso de esto?

**Comment by JavierCane** [comment]
Buenas @rpalaciosg, sorry por la demora en contestar.

El tema es que este repositorio está en desarrollo aún. Efectivamente servirá como ejemplos para un futuro curso de DDD en TypeScript. No obstante, aún queda algo de tiempo para que lo empecemos a grabar y demás.

Mientras tanto, puedes aprovechar el [orden en el que solemos recomendar hacer los cursos para aprender DDD](https://soporte.codely.tv/es/articles/4187948-en-que-orden-hacer-los-cursos):

1. [Principios SOLID Aplicados](https://pro.codely.tv/library/principios-solid-aplicados)
2. [Arquitectura Hexagonal](https://pro.codely.tv/library/arquitectura-hexagonal)
3. [Testing: Introducción y buenas prácticas](https://pro.codely.tv/library/testing-introduccion-y-buenas-practicas)
4. [CQRS](https://pro.codely.tv/library/cqrs-command-query-responsibility-segregation-3719e4aa)
5. [Event-Driven Architecture](https://pro.codely.tv/library/comunicacion-entre-microservicios-event-driven-architecture)
6. [Domain-Driven Design Aplicado](https://pro.codely.tv/library/domain-driven-design-ddd)
7. [DDD en PHP](https://pro.codely.tv/library/ddd-en-php) o [DDD en Java](https://pro.codely.tv/library/ddd-en-java)
8. [CQRS+Event Sourcing](https://pro.codely.tv/library/cqrs-y-event-sourcing-con-kotlin-y-axon-framework)

En un futuro en el paso 7 tendrás también disponible el curso que estamos preparando al que hace referencia este repositorio. Mientras tanto, puedes cursar toda esa serie e irte apoyando en los ejemplos del repositorio por ti mismo ya que los conceptos a nivel teórico son los mismos. 😊

Un saludo, muchisísimas gracias por el interés, y cualquier cosa aquí estamos 🤟

**Comment by rpalaciosg** [comment]
Muchas gracias Javi, 👌
